# 此工作流的名字
name: Build
# 自动执行
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
# 工作/任务，这里的工作是可以并行的。
jobs:
  # 工作的名称“编译windows版”
  buildwin:
    # 运行的操作系统 windows server latest
    runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ windows-latest ]
    # 步骤
    steps:
      # 使用预制action：拉取最新的代码
      - uses: actions/checkout@v3
      # 步骤一的名称：
      - name: Install and Build
        # 该步骤运行的终端命令，进入仓库的目录，安装依赖，运行编译命令
        run:
          yarn && yarn build
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}

